---
driver:
  name: vagrant
  vagrantfiles:
    - vagrantfile-block.rb

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[etcd-test::default]
    attributes:
