---
driver:
  name: vagrant
  vagrantfiles:
    - vagrantfile-block.rb

provisioner:
  name: chef_solo

platforms:
  - name: debian-8.7

suites:
  - name: default
    run_list:
      - recipe[etcd-test::default]
    attributes:
