---
driver:
  name: vagrant
  vagrantfiles:
    - vagrantfile-block.rb

provisioner:
  name: chef_solo

platforms:
  - name: debian-8.7

suites:
  - name: default
    run_list:
      - recipe[etcd-test::add_sid_repo]
      - recipe[etcd-test::add_local_repo]
      - recipe[etcd-test::install_etcd_client]
      - recipe[etcd-test::install_etcd_server]
    attributes:
  - name: default-transitional
    run_list:
      - recipe[etcd-test::add_sid_repo]
      - recipe[etcd-test::add_local_repo]
      - recipe[etcd-test::install_etcd]
    attributes:
  - name: cluster
    run_list:
      - recipe[etcd-test::add_sid_repo]
      - recipe[etcd-test::add_local_repo]
      - recipe[etcd-test::install_docker]